#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#xrandr --output eDP-1 --mode 1600x900 &
#xwallpaper --zoom wall.jpg &
feh --bg-fill ~/Pictures/wall.jpg &
xrandr --output Virtual-1 --mode 1366x768 &


bspc monitor -d I II III IV V

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
bspc config focused_border_color "#262626"
bspc config normal_border_color "#262626"
bspc config active_border_color "#262626"
## Use the line below if you are on bspwm >= 0.9.4
#bspc config presel_feedback_color "$color1"
## Use the line below if you are on bspwm < 0.9.4
##bspc config presel_border_color "$color1"

bspc config border_width         2
bspc config window_gap           -1 
#bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding 0
#bspc config top_padding 20
bspc config top_padding 33 


# Remove x cursor
#xsetroot -cursor_name left_ptr &

#Polybar Launching
~/.config/polybar/./launch.sh

#enable touchpad tapping and natural scrolling
#xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
#xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
